/*
 * Writes down what this processor answers for the two approximations the rasteriser divides by.
 *
 * Both instructions are table lookups: the answer depends on the top bits of the mantissa and on
 * nothing else below them, and the exponent only shifts it. Reading that table off one processor
 * lets every other processor give the same answers, which is what makes a picture drawn on one
 * machine checkable on another.
 *
 * The instruction set fixes only how far these answers may be from the truth, not what they are,
 * so two processors are free to disagree and both be right. Apple's translation and real x86
 * hardware do disagree, which is why the table is carried rather than the instruction.
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <xmmintrin.h>

#include "../sw3d/reciprocal-answers.h"

/** The reciprocal answers one of these for every run of mantissas that share the top bits. */
enum { RECIPROCAL_ENTRIES = 2048, RECIPROCAL_DROPPED = 12 };

/** The inverse root answers half as many, once for each parity of the exponent. */
enum { ROOT_ENTRIES = 1024, ROOT_DROPPED = 13 };

static uint32_t bits(float value) {
    uint32_t held;
    memcpy(&held, &value, sizeof held);
    return held;
}

static float from(uint32_t held) {
    float value;
    memcpy(&value, &held, sizeof value);
    return value;
}

static uint32_t reciprocalOf(uint32_t held) {
    return bits(_mm_cvtss_f32(_mm_rcp_ss(_mm_set_ss(from(held)))));
}

static uint32_t inverseRootOf(uint32_t held) {
    return bits(_mm_cvtss_f32(_mm_rsqrt_ss(_mm_set_ss(from(held)))));
}

/** The exponent of a float that stands in the range the table is read over. */
static uint32_t standing(uint32_t exponent) {
    return exponent << 23;
}

static void writeTable(const char *name, int entries, int dropped, uint32_t exponent,
                       uint32_t (*answer)(uint32_t)) {
    printf("const uint32_t %s[%d] = {", name, entries);

    for (int i = 0; i < entries; i++) {
        printf("%s0x%08x,", i % 6 == 0 ? "\n    " : " ",
               answer(standing(exponent) | ((uint32_t) i << dropped)));
    }

    printf("\n};\n\n");
}

/**
 * Says how many answers in one table this processor gives differently from the table the toolkit
 * carries, and how far apart the worst two are, counted in floats.
 */
static int compareTable(const char *name, const uint32_t *carried, int entries, int dropped,
                        uint32_t exponent, uint32_t (*answer)(uint32_t)) {
    int differ = 0;
    uint32_t worst = 0;

    for (int i = 0; i < entries; i++) {
        uint32_t mine = answer(standing(exponent) | ((uint32_t) i << dropped));
        if (mine != carried[i]) {
            uint32_t apart = mine > carried[i] ? mine - carried[i] : carried[i] - mine;
            worst = apart > worst ? apart : worst;
            differ++;
        }
    }

    printf("%-20s %5d of %5d entries differ, worst %u floats apart\n", name, differ, entries,
           worst);
    return differ;
}

/**
 * Compares what this processor answers with what the toolkit carries, for a machine asked to
 * check rather than to write the table again.
 */
static void compare(void) {
    int differ = compareTable("RECIPROCAL_ANSWERS", RECIPROCAL_ANSWERS, RECIPROCAL_ENTRIES,
                              RECIPROCAL_DROPPED, 127, reciprocalOf)
        + compareTable("ROOT_ANSWERS_EVEN", ROOT_ANSWERS_EVEN, ROOT_ENTRIES, ROOT_DROPPED, 126,
                       inverseRootOf)
        + compareTable("ROOT_ANSWERS_ODD", ROOT_ANSWERS_ODD, ROOT_ENTRIES, ROOT_DROPPED, 127,
                       inverseRootOf);

    if (differ == 0) {
        printf("\nThis processor answers exactly what the toolkit carries.\n");
    } else {
        printf("\nThis processor answers differently. The toolkit carries a table for this reason,"
               " so its pictures are the same here anyway.\n");
    }
}

static void writeTables(void) {
    printf("/*\n"
           " * What one processor answered, written down so that every other one can answer the\n"
           " * same. Generated by natives/src/main/native/reciprocal/capture.c. Do not edit.\n"
           " */\n\n");
    printf("#include <stdint.h>\n\n");

    /* Read over [1, 2), which every other range is the same answer with a shifted exponent. */
    writeTable("RECIPROCAL_ANSWERS", RECIPROCAL_ENTRIES, RECIPROCAL_DROPPED, 127, reciprocalOf);

    /* A square root halves the exponent, so an odd one and an even one answer differently. */
    writeTable("ROOT_ANSWERS_EVEN", ROOT_ENTRIES, ROOT_DROPPED, 126, inverseRootOf);
    writeTable("ROOT_ANSWERS_ODD", ROOT_ENTRIES, ROOT_DROPPED, 127, inverseRootOf);
}

/**
 * Writes the table this processor answers to standard output, or with --compare says how it
 * differs from the table the toolkit already carries.
 */
int main(int count, char **given) {
    if (count > 1 && strcmp(given[1], "--compare") == 0) {
        compare();
    } else {
        writeTables();
    }

    return 0;
}
